# Jared Adams 00865234

## You are allowed and encouraged to search and get help from any resource, but write down the code by your own hands. 

In [2]:
import numpy as np

### Your work: 

Create a new cell right below this cell. In the new cell, write one or a few statements that create and print a $3 \times 4$ (ie., 3 rows by 4 columns)  ndarray of random numbers from the range $[0,1)$. The result should be something similar to the following (numbers could be different): 

[[0.21559175 0.71091185 0.78264013 0.0816029 ]

 [0.86528926 0.43816422 0.9406306  0.54750664]

[0.794279   0.48067576 0.97565906 0.72432521]]

In [34]:
newA = np.array([[np.random.random(1)[0] for i in range(4)] for i in range(3)])
print(newA)

[[0.84915237 0.02139142 0.73280251 0.04017641]
 [0.66873862 0.39775511 0.26407101 0.27108524]
 [0.19969016 0.42265417 0.38325703 0.6503135 ]]


In [57]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the transpose of matrix $a$ defined above. The print should be looking like this: 

[[1 4]

 [2 5]

[3 6]]

In [52]:
print(np.array(a).transpose())

[[1 4]
 [2 5]
 [3 6]]


In [79]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the multiplication of matrix a and matrix b that are definded above. The print should be looking like this: 

[[ 38  44  50  56]

 [ 83  98 113 128]]


In [32]:
c = np.array([[10,20,30],[40,50,60]])
print(c)

[[10 20 30]
 [40 50 60]]


In [60]:
multiMatrix = np.dot(a,b)
print(multiMatrix)

[[ 38  44  50  56]
 [ 83  98 113 128]]


### Your work:
Creat a new cell right below this cell. In the new cell, write one or a few statements that print the element-wise (also called component-wise) multiplication of matrix a and matrix c that definded above. The print should be looking like this: 

[[ 10  40  90]

 [160 250 360]]

In [55]:
print(np.multiply(a, c))

[[ 10  40  90]
 [160 250 360]]


### Your work:

Creat a new cell right below this cell. In the new cell, write one or a few statements that add a new column to matrix b (the newly added column becomes the 0th column), and save the resuling new matrix to d (without changing b), then print d. The print should be looking like this: 

[[ 1  1  2  3  4]

 [ 1  5  6  7  8]

[ 1  9 10 11 12]]

Hint: Use np.insert() method. Search and read its document. 

In [81]:
e = np.array([1,2,3])
print(e)

[1 2 3]


In [80]:
d = np.insert(b, 0, np.array((1, 1, 1)),1)
print(d)

[[ 1  1  2  3  4]
 [ 1  5  6  7  8]
 [ 1  9 10 11 12]]


### Your work:

Creat a new cell right below this cell. In the new cell, write one or a few statements that prints the inverse of e. The result should be the following: 

    [[1]

     [2]

    [3]]

Hint: Study the reshape function. You need to increase the ndim of the ndarray from 1 to 2, then the transpose function can work. 

In [96]:
print(e.reshape(1, 3).transpose())

[[1]
 [2]
 [3]]
